[[
  {
    "name": "symfony.messenger.consume",
    "service": "symfony_messenger_test",
    "resource": "async -> App\\Message\\LuckyNumberNotification",
    "trace_id": 0,
    "span_id": 1,
    "parent_id": 7988579250813780765,
    "type": "queue",
    "error": 1,
    "meta": {
      "_dd.p.dm": "0",
      "_dd.p.tid": "66962d5c00000000",
      "component": "symfonymessenger",
      "error.message": "Uncaught Symfony\\Component\\Messenger\\Exception\\UnrecoverableMessageHandlingException: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/src/MessageHandler/LuckyNumberNotificationHandler.php:15",
      "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(157): App\\MessageHandler\\LuckyNumberNotificationHandler->__invoke()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(96): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->callHandler()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#18 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#19 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#20 {main}\n\nNext Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129\nStack trace:\n#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
      "error.type": "Symfony\\Component\\Messenger\\Exception\\UnrecoverableMessageHandlingException",
      "messaging.destination": "async",
      "messaging.destination_kind": "queue",
      "messaging.operation": "receive",
      "messaging.symfony.bus": "messenger.bus.default",
      "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
      "messaging.system": "symfony",
      "runtime-id": "fea32442-56ef-4827-85d8-4cd4123aced0",
      "span.kind": "consumer"
    },
    "metrics": {
      "_sampling_priority_v1": 1
    }
  },
     {
       "name": "symfony.Symfony\\Component\\Messenger\\Event\\WorkerMessageReceivedEvent",
       "service": "symfony_messenger_test",
       "resource": "symfony.Symfony\\Component\\Messenger\\Event\\WorkerMessageReceivedEvent",
       "trace_id": 0,
       "span_id": 2,
       "parent_id": 1,
       "type": "queue",
       "meta": {
         "component": "symfony"
       }
     },
     {
       "name": "symfony.messenger.dispatch",
       "service": "symfony_messenger_test",
       "resource": "async -> App\\Message\\LuckyNumberNotification",
       "trace_id": 0,
       "span_id": 3,
       "parent_id": 1,
       "type": "queue",
       "error": 1,
       "meta": {
         "component": "symfonymessenger",
         "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
         "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
         "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
         "messaging.destination": "async",
         "messaging.destination_kind": "queue",
         "messaging.operation": "process",
         "messaging.symfony.bus": "messenger.bus.default",
         "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
         "messaging.system": "symfony"
       },
       "metrics": {
         "messaging.symfony.stamps.DDTrace\\Integrations\\SymfonyMessenger\\DDTraceStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Bridge\\Redis\\Transport\\RedisReceivedStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\AckStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\BusNameStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\ConsumedByWorkerStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\ReceivedStamp": 1
       }
     },
        {
          "name": "symfony.messenger.middleware",
          "service": "symfony_messenger_test",
          "resource": "Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware",
          "trace_id": 0,
          "span_id": 5,
          "parent_id": 3,
          "type": "queue",
          "error": 1,
          "meta": {
            "component": "symfonymessenger",
            "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
            "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
            "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
            "messaging.destination": "async",
            "messaging.destination_kind": "queue",
            "messaging.operation": "process",
            "messaging.symfony.bus": "messenger.bus.default",
            "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
            "messaging.system": "symfony"
          }
        },
           {
             "name": "symfony.messenger.middleware",
             "service": "symfony_messenger_test",
             "resource": "Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware",
             "trace_id": 0,
             "span_id": 6,
             "parent_id": 5,
             "type": "queue",
             "error": 1,
             "meta": {
               "component": "symfonymessenger",
               "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
               "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
               "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
               "messaging.destination": "async",
               "messaging.destination_kind": "queue",
               "messaging.operation": "process",
               "messaging.symfony.bus": "messenger.bus.default",
               "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
               "messaging.system": "symfony"
             }
           },
              {
                "name": "symfony.messenger.middleware",
                "service": "symfony_messenger_test",
                "resource": "Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware",
                "trace_id": 0,
                "span_id": 7,
                "parent_id": 6,
                "type": "queue",
                "error": 1,
                "meta": {
                  "component": "symfonymessenger",
                  "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                  "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                  "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                  "messaging.destination": "async",
                  "messaging.destination_kind": "queue",
                  "messaging.operation": "process",
                  "messaging.symfony.bus": "messenger.bus.default",
                  "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                  "messaging.system": "symfony"
                }
              },
                 {
                   "name": "symfony.messenger.middleware",
                   "service": "symfony_messenger_test",
                   "resource": "Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware",
                   "trace_id": 0,
                   "span_id": 8,
                   "parent_id": 7,
                   "type": "queue",
                   "error": 1,
                   "meta": {
                     "component": "symfonymessenger",
                     "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                     "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                     "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                     "messaging.destination": "async",
                     "messaging.destination_kind": "queue",
                     "messaging.operation": "process",
                     "messaging.symfony.bus": "messenger.bus.default",
                     "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                     "messaging.system": "symfony"
                   }
                 },
                    {
                      "name": "symfony.messenger.middleware",
                      "service": "symfony_messenger_test",
                      "resource": "Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware",
                      "trace_id": 0,
                      "span_id": 9,
                      "parent_id": 8,
                      "type": "queue",
                      "error": 1,
                      "meta": {
                        "component": "symfonymessenger",
                        "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                        "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                        "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                        "messaging.destination": "async",
                        "messaging.destination_kind": "queue",
                        "messaging.operation": "process",
                        "messaging.symfony.bus": "messenger.bus.default",
                        "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                        "messaging.system": "symfony"
                      }
                    },
                       {
                         "name": "symfony.messenger.middleware",
                         "service": "symfony_messenger_test",
                         "resource": "Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware",
                         "trace_id": 0,
                         "span_id": 10,
                         "parent_id": 9,
                         "type": "queue",
                         "error": 1,
                         "meta": {
                           "component": "symfonymessenger",
                           "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                           "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                           "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                           "messaging.destination": "async",
                           "messaging.destination_kind": "queue",
                           "messaging.operation": "process",
                           "messaging.symfony.bus": "messenger.bus.default",
                           "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                           "messaging.system": "symfony"
                         }
                       },
                          {
                            "name": "symfony.messenger.middleware",
                            "service": "symfony_messenger_test",
                            "resource": "Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware",
                            "trace_id": 0,
                            "span_id": 11,
                            "parent_id": 10,
                            "type": "queue",
                            "error": 1,
                            "meta": {
                              "component": "symfonymessenger",
                              "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                              "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                              "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                              "messaging.destination": "async",
                              "messaging.destination_kind": "queue",
                              "messaging.operation": "process",
                              "messaging.symfony.bus": "messenger.bus.default",
                              "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                              "messaging.system": "symfony"
                            }
                          },
                             {
                               "name": "symfony.messenger.handle",
                               "service": "symfony_messenger_test",
                               "resource": "App\\MessageHandler\\LuckyNumberNotificationHandler",
                               "trace_id": 0,
                               "span_id": 12,
                               "parent_id": 11,
                               "type": "queue",
                               "error": 1,
                               "meta": {
                                 "component": "symfonymessenger",
                                 "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\UnrecoverableMessageHandlingException: Number is out of bounds in /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/src/MessageHandler/LuckyNumberNotificationHandler.php:15",
                                 "error.stack": "#0 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(157): App\\MessageHandler\\LuckyNumberNotificationHandler->__invoke()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(96): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->callHandler()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#6 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#7 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#8 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#9 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#10 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#11 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#12 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#13 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#14 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#15 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#16 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#17 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#18 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#19 /home/circleci/datadog/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#20 {main}",
                                 "error.type": "Symfony\\Component\\Messenger\\Exception\\UnrecoverableMessageHandlingException",
                                 "messaging.destination_kind": "queue",
                                 "messaging.operation": "process",
                                 "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                                 "messaging.system": "symfony"
                               }
                             },
     {
       "name": "symfony.Symfony\\Component\\Messenger\\Event\\WorkerMessageFailedEvent",
       "service": "symfony_messenger_test",
       "resource": "symfony.Symfony\\Component\\Messenger\\Event\\WorkerMessageFailedEvent",
       "trace_id": 0,
       "span_id": 4,
       "parent_id": 1,
       "type": "queue",
       "meta": {
         "component": "symfony"
       }
     }]]
