[[
  {
    "name": "symfony.request",
    "service": "test_symfony_23",
    "resource": "error",
    "trace_id": 0,
    "span_id": 1,
    "parent_id": 8755573594811919325,
    "type": "web",
    "error": 1,
    "meta": {
      "_dd.p.dm": "-0",
      "_dd.p.tid": "6661bb9f00000000",
      "component": "symfony",
      "error.message": "Uncaught Exception (500): An exception occurred in /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/src/AppBundle/Controller/CommonScenariosController.php:40",
      "error.stack": "#0 [internal function]: AppBundle\\Controller\\CommonScenariosController->errorAction()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/app/bootstrap.php.cache(2978): call_user_func_array()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/app/bootstrap.php.cache(2952): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/app/bootstrap.php.cache(3081): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/app/bootstrap.php.cache(2351): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/web/app.php(14): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#6 {main}",
      "error.type": "Exception",
      "http.method": "GET",
      "http.status_code": "500",
      "http.url": "http://localhost:9999/error?key=value&<redacted>",
      "runtime-id": "264f8207-13c8-42ee-bd15-24d728192870",
      "span.kind": "server",
      "symfony.route.action": "AppBundle\\Controller\\CommonScenariosController@errorAction",
      "symfony.route.name": "error"
    },
    "metrics": {
      "_sampling_priority_v1": 1.0
    }
  },
     {
       "name": "symfony.httpkernel.kernel.handle",
       "service": "test_symfony_23",
       "resource": "AppKernel",
       "trace_id": 0,
       "span_id": 2,
       "parent_id": 1,
       "type": "web",
       "meta": {
         "component": "symfony",
         "span.kind": "server"
       }
     },
        {
          "name": "symfony.httpkernel.kernel.boot",
          "service": "test_symfony_23",
          "resource": "AppKernel",
          "trace_id": 0,
          "span_id": 4,
          "parent_id": 2,
          "type": "web",
          "meta": {
            "component": "symfony"
          }
        },
        {
          "name": "symfony.kernel.handle",
          "service": "test_symfony_23",
          "resource": "symfony.kernel.handle",
          "trace_id": 0,
          "span_id": 5,
          "parent_id": 2,
          "type": "web",
          "meta": {
            "component": "symfony"
          }
        },
           {
             "name": "symfony.kernel.request",
             "service": "test_symfony_23",
             "resource": "symfony.kernel.request",
             "trace_id": 0,
             "span_id": 6,
             "parent_id": 5,
             "type": "web",
             "meta": {
               "component": "symfony"
             }
           },
           {
             "name": "symfony.kernel.controller",
             "service": "test_symfony_23",
             "resource": "symfony.kernel.controller",
             "trace_id": 0,
             "span_id": 7,
             "parent_id": 5,
             "type": "web",
             "meta": {
               "component": "symfony"
             }
           },
           {
             "name": "symfony.controller",
             "service": "test_symfony_23",
             "resource": "AppBundle\\Controller\\CommonScenariosController::errorAction",
             "trace_id": 0,
             "span_id": 8,
             "parent_id": 5,
             "type": "web",
             "error": 1,
             "meta": {
               "component": "symfony",
               "error.message": "Thrown Exception (500): An exception occurred in /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/src/AppBundle/Controller/CommonScenariosController.php:40",
               "error.stack": "#0 [internal function]: AppBundle\\Controller\\CommonScenariosController->errorAction()\n#1 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/app/bootstrap.php.cache(2978): call_user_func_array()\n#2 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/app/bootstrap.php.cache(2952): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()\n#3 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/app/bootstrap.php.cache(3081): Symfony\\Component\\HttpKernel\\HttpKernel->handle()\n#4 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/app/bootstrap.php.cache(2351): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle()\n#5 /home/circleci/datadog/tests/Frameworks/Symfony/Version_2_3/web/app.php(14): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#6 {main}",
               "error.type": "Exception"
             }
           },
           {
             "name": "symfony.kernel.handleException",
             "service": "test_symfony_23",
             "resource": "symfony.kernel.handleException",
             "trace_id": 0,
             "span_id": 9,
             "parent_id": 5,
             "type": "web",
             "meta": {
               "component": "symfony"
             }
           },
              {
                "name": "symfony.kernel.exception",
                "service": "test_symfony_23",
                "resource": "symfony.kernel.exception",
                "trace_id": 0,
                "span_id": 10,
                "parent_id": 9,
                "type": "web",
                "meta": {
                  "component": "symfony"
                }
              },
                 {
                   "name": "symfony.kernel.request",
                   "service": "test_symfony_23",
                   "resource": "symfony.kernel.request",
                   "trace_id": 0,
                   "span_id": 12,
                   "parent_id": 10,
                   "type": "web",
                   "meta": {
                     "component": "symfony"
                   }
                 },
                 {
                   "name": "symfony.kernel.controller",
                   "service": "test_symfony_23",
                   "resource": "symfony.kernel.controller",
                   "trace_id": 0,
                   "span_id": 13,
                   "parent_id": 10,
                   "type": "web",
                   "meta": {
                     "component": "symfony"
                   }
                 },
                 {
                   "name": "symfony.controller",
                   "service": "test_symfony_23",
                   "resource": "Symfony\\Bundle\\TwigBundle\\Controller\\ExceptionController::showAction",
                   "trace_id": 0,
                   "span_id": 14,
                   "parent_id": 10,
                   "type": "web",
                   "meta": {
                     "component": "symfony"
                   }
                 },
                    {
                      "name": "symfony.templating.render",
                      "service": "test_symfony_23",
                      "resource": "Twig_Environment TwigBundle:Exception:error.html.twig",
                      "trace_id": 0,
                      "span_id": 16,
                      "parent_id": 14,
                      "type": "web",
                      "meta": {
                        "component": "symfony"
                      }
                    },
                 {
                   "name": "symfony.kernel.response",
                   "service": "test_symfony_23",
                   "resource": "symfony.kernel.response",
                   "trace_id": 0,
                   "span_id": 15,
                   "parent_id": 10,
                   "type": "web",
                   "meta": {
                     "component": "symfony"
                   }
                 },
              {
                "name": "symfony.kernel.response",
                "service": "test_symfony_23",
                "resource": "symfony.kernel.response",
                "trace_id": 0,
                "span_id": 11,
                "parent_id": 9,
                "type": "web",
                "meta": {
                  "component": "symfony"
                }
              },
     {
       "name": "symfony.kernel.terminate",
       "service": "test_symfony_23",
       "resource": "symfony.kernel.terminate",
       "trace_id": 0,
       "span_id": 3,
       "parent_id": 1,
       "type": "web",
       "meta": {
         "component": "symfony"
       }
     }]]
